### ISSUE TITLE
Config error  `ConfigEntryNotReady`

### ISSUE THREAD

**Issue by nivv** [hasscc/petkit#23]
As of today I'm getting this error:

```
2022-09-14 19:55:00 ERROR (MainThread) [homeassistant.setup] Error during setup of component petkit
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
self.data = await self._async_update_data()
File "/config/custom_components/petkit/__init__.py", line 239, in _async_update_data
dls = await self.account.get_devices()
File "/config/custom_components/petkit/__init__.py", line 216, in get_devices
rsp = await self.request(api)
File "/config/custom_components/petkit/__init__.py", line 163, in request
req = await self.http.request(method, url, **kws)
File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
await resp.start(conn)
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 913, in start
self._continue = None
File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
result = await task
File "/config/custom_components/petkit/__init__.py", line 86, in async_setup
await coordinator.async_config_entry_first_refresh()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_config_entry_first_refresh
raise ex
homeassistant.exceptions.ConfigEntryNotReady
```
Before this error is thrown this warning is raised:

```
Logger: homeassistant.setup
Source: /usr/local/lib/python3.9/asyncio/events.py:80
First occurred: 19:54:49 (1 occurrences)
Last logged: 19:54:49

Setup of petkit is taking over 10 seconds.
```

**Comment by nivv** [comment]
The app on iOS behaves weirdly as well. Maybe they're having issues. Anyone else experiencing this?

**Comment by fhornrudd** [comment]
I think the petkit servers are down currently

**Comment by tzwickl** [comment]
I see the same error in my logs but my Petkit App is working fine...

**Comment by fhornrudd** [comment]
My app looks like it is working but gives errors eventually for anything, does not allow any actions

**Comment by fhornrudd** [comment]
App started working. Restarted HA and it loaded the component correctly for me

**Comment by nivv** [comment]
@fhornrudd Integration works for me too. Closing this!
