### ISSUE TITLE
I got a strange error with the newest version of petkit integration.

### ISSUE THREAD

**Issue by khkl** [hasscc/petkit#27]
Logger: custom_components.petkit
Source: custom_components/petkit/button.py:6
Integration: Petkit (documentation, issues)
First occurred: 17:57:24 (1 occurrences)
Last logged: 17:57:24

Unexpected error fetching petkit-****-devices data: No module named 'homeassistant.components.button'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/home/homeassistant/.homeassistant/custom_components/petkit/__init__.py", line 266, in _async_update_data
    await self.update_hass_entities(d, dvc)
  File "/home/homeassistant/.homeassistant/custom_components/petkit/__init__.py", line 272, in update_hass_entities
    from .button import PetkitButtonEntity
  File "/home/homeassistant/.homeassistant/custom_components/petkit/button.py", line 6, in <module>
    from homeassistant.components.button import (
ModuleNotFoundError: No module named 'homeassistant.components.button'

**Comment by al-one** [comment]
Upgrade your HA core.
